### ISSUE TITLE
Front-End - Web App [Part 2]

### ISSUE THREAD

**Issue by JessePeplinski** [JessePeplinski/tcg-scraper#7]
Use Django or Flask

Views
- [ ] All cards
- [ ] Subscribed cards

Cards display
- [ ] Low market value
- [ ] Market value
- [ ] High market value

Functionality
- [ ] onClick, subscribe to card via "Subscribe" button
- [ ] onClick, unsubscribe to card via "Unsubscribe" button

Create users
- [ ] SSO
- [ ] Users can sign in and see all the cards they have subscribed to

Metrics
- [ ] View most subscribed cards
